#
# .github/workflows/build-docs.yml
#
# Copyright 2021 Jens A. Koch.
# SPDX-License-Identifier: BSL-1.0
# This file is part of ttauri-project.
#

name: Documentation Pipeline

on: push

jobs:

  build-docs:
    name: Generate Documentation

    # The base container to run the job on.
    # "ubuntu-latest" is still stuck on 18.04, see https://github.com/actions/virtual-environments/issues/1816
    # Let's use a newer version...
    runs-on: ubuntu-20.04

    # debian sid needs no sudo
    #container:
    #  image: debian:sid-slim

    steps:
      # Checks out a copy of your repository
      - name: 🤘 Checkout Code
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      # Install tools for documentation generation
      - name: 🔽 Install Tools
        # sudo apt-get upgrade -y
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -y
          sudo apt-get install -y doxygen graphviz

      # Show the version of the tools we use, e.g. Doxygen. Graphviz version is displayed via "dot".
      - name: 🛈 Show Tool Versions
        run: |
          doxygen -v
          dot -V

      # Get the source repository, for which we want to generate the documentation for.
      # Then fetch all tagged versions.
      - name: 🔽 Get Source Repository
        run: |
          rm -rf ttauri
          git clone https://github.com/ttauri-project/ttauri.git ttauri

      # Get the list of version numbers from git tags.
      # Use reverse version sorting of "git tag list".
      # Append "main" branch to version list.
      # Write to "version.txt"
      #
      # Get latest tag version without "v" prefix.
      # Write to "latest_version.txt".
      - name: Get Versions
        run: |
          cd ttauri
          (echo "main" && git tag -l --sort=-version:refname "v*") > ../versions.txt
          git tag --sort=committerdate | tail -1 | cut -c2- > ../latest_version.txt
          echo "Available versions:"
          cat ../versions.txt
          echo "Latest version:"
          cat ../latest_version.txt

      # Run doxygen on the checkouts of each tags to generate documentation for each version.
      - name: 🙏 Build documentation for all tags
        run: |
          chmod +x scripts/build_docs_gh.sh
          scripts/build_docs_gh.sh

      - name: 🖉 Set Repository
        run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: ✓ Commit
        run: |
          cd docs
          git init
          git add -A
          git config --local user.email "github-actions[bot]@users.noreply.ttauri-project.org"
          git config --local user.name "github-actions[bot]"
          git commit -m "Publish docs from ${GITHUB_REPOSITORY}@${GITHUB_SHA:0:9}"

      - name: 🚀 push
        uses: ad-m/github-push-action@v0.6.0 # https://github.com/ad-m/github-push-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #repository: jakoch/${{ env.REPOSITORY }}
          branch: gh-pages
          directory: ./docs
          force: true

      # Automatically removes all workflow runs older than 7 days, but always keeps the last run.
      - name: ✗ Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 1
